---
name: Build

on:
  pull_request:
  push:

permissions: {}

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install SDL3
        run: |
          sudo apt-get update
          sudo apt-get install libsdl3-dev
      - name: Build Stella
        run: |
          ./configure && make -j2 all

  macos:
    name: macOS
    runs-on: macos-latest
    env:
      SDL3_version: 3.2.14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: Check out the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install SDL3
        run: |
          curl https://www.libsdl.org/release/SDL3-$SDL3_version.tar.gz | tar xzf -
          mkdir SDL3-$SDL3_version/build
          cd SDL3-$SDL3_version/build
          ../configure && make -j3 && sudo make install
      - name: Build Stella
        run: |
          ./configure && make -j3 all

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
    env:
      Platform: ${{ matrix.platform }}
      SDL3_version: 3.2.14
    steps:
      - name: Check out the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Set up MSBUILD
        uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506
      - name: Install SDL3
        shell: cmd
        run: |
          curl -o "C:\SDL3-devel.zip" "https://www.libsdl.org/release/SDL3-devel-%SDL3_version%-VC.zip"
          7z x "C:\SDL3-devel.zip" -o"C:\"
          xcopy /S "C:\SDL3-%SDL3_version%\include" src\common
          if %Platform%==x64 xcopy /S "C:\SDL3-%SDL3_version%\lib\x64" src\os\windows

      - name: Build Stella
        run: |
          msbuild src\os\windows\Stella.sln
